@startuml
title CLA validation flow, with CLA signing

User -> GitHub: 1) creates a pull request
GitHub -> CLA_App: 2) web hook pull request event
CLA_App -> GitHub: 3) reads a list of committers emails
CLA_App -> EdgeDB: 4) fetches signed CLA\n by committers emails
CLA_App -> GitHub: 5) publishes a negative status\n (using the configured GitHub app)
note right: the status contains a URL to\n a page that displays the CLA to sign,\n with a link to sign-in using the configured OAuth app
CLA_App -> EdgeDB: 6) checks if a comment was\n already published for the PR
CLA_App -> GitHub: 7) creates or updates a comment\n with status badge
note right: the comment increases visibility,\nthe status badge is served by the CLA_App itself
GitHub -> User: 8) the PR page displays a negative\n status, and comment
User -> GitHub: 9) the user clicks on the link under\n the comment, or status check on GitHub UI
GitHub -> CLA_App: 10) the user navigates to the CLA page
note right: /contributor-license-agreement\nthe URL contains a state handled by OAuth flow
CLA_App -> EdgeDB: 11) fetches the current agreement by PR repository
CLA_App -> User: 12) displays the CLA page to the end user, with a link to sign-in with the configured OAuth app
note right: the user can read the CLA, and click the button to sign
... //the user reads the CLA...// ...
User -> CLA_App: 13) the user clicks on the sign-in link
CLA_App -> GitHub: 14) the user is redirected to a page\n to authorize the configured OAuth app
GitHub -> User: 15) if the user never authorized the app,\n the GitHub app prompt for permissions
GitHub -> CLA_App: 16) handles redirect to the configured redirect_uri
CLA_App -> GitHub: 17) uses the obtained token to fetch an access token for the user
CLA_App -> GitHub: 18) uses the access token to fetch a list of emails of the user
CLA_App -> EdgeDB: 19) creates a signed CLA for each\n verified email owned by the user
CLA_App -> EdgeDB: 20) verifies if all committers signed the CLA
CLA_App -> GitHub: 21) updates the published comment to display a green badge
CLA_App -> GitHub: 22) updates the existing status to mark it as success
GitHub -> User: 23) GitHub UI shows a green status
note right: the status contains a URL to\n a page that displays the signed CLA
@endumld
