@startuml
title CLA validation flow, CLA already signed

User -> GitHub: 1) creates a pull request
GitHub -> CLA_App: 2) web hook pull request event
CLA_App -> GitHub: 3) reads a list of committers emails
CLA_App -> EdgeDB: 4) fetches signed CLA\n by committers emails
CLA_App -> GitHub: 5) publishes a positive status\n (using the configured GitHub app)
note right: the status contains a URL to\n a page that displays the signed CLA
GitHub -> User: 6) the PR page displays\n the positive status check

@endumld
