name: "build-test"

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        yarn install
    - name: Run tslint tests
      run: |
        yarn tslint --project .
    - name: Run tests
      run: |
        npm t
